# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GgR1msvDhmQh1y5mPDA5naXHDvfWD0UB
"""

import asyncio
import threading
import time
from fastapi import FastAPI
import pandas as pd
import plotly.graph_objects as go
import streamlit as st
import uvicorn

# ==========================================
# 1. FASTAPI BACKEND (Arka Plan Veri Akışı)
# ==========================================
app = FastAPI()


def load_data():
    # Veri setini yerel dizinden oku
    df = pd.read_csv(
        "household_power_consumption.txt",
        sep=";",
        low_memory=False,
        na_values=["?"],
        nrows=50000,
    )
    df.ffill(inplace=True)
    df["Timestamp"] = pd.to_datetime(
        df["Date"] + " " + df["Time"], format="%d/%m/%Y %H:%M:%S"
    )
    cols = ["Global_active_power", "Voltage", "Global_intensity"]
    for c in cols:
        df[c] = df[c].astype(float)
    return df


try:
    energy_df = load_data()
    print("✅ Kaggle Veri Seti Yerel Hafızaya Yüklendi.")
except Exception as e:
    print(f"⚠️ Veri okunurken hata oluştu: {e}")
    energy_df = None


def run_fastapi():
    uvicorn.run(app, host="127.0.0.1", port=8000, log_level="error")


# FastAPI'yi Streamlit'i engellememesi için ayrı bir iş parçacığında (thread) çalıştır
threading.Thread(target=run_fastapi, daemon=True).start()

# ==========================================
# 2. STREAMLIT FRONTEND (Arayüz & Dashboard)
# ==========================================
st.set_page_config(
    page_title="Enerji Takip Dashboard", page_icon="⚡", layout="wide"
)

st.title("⚡ Akıllı Enerji Tüketim Dashboard'u")
st.caption(
    "Gerçek Zamanlı Kaggle Sensör Akışı & Anomali Tespit Sistemi"
)

# Üst Metrik Paneli
col1, col2, col3 = st.columns(3)
with col1:
    status_metric = st.empty()
with col2:
    power_metric = st.empty()
with col3:
    voltage_metric = st.empty()

# Canlı Grafik Alanı
chart_spot = st.empty()

# Streamlit Session State (Hafıza Yönetimi)
if "history" not in st.session_state:
    st.session_state.history = {"time": [], "power": []}

# Canlı Akış Döngüsü
if energy_df is not None:
    for index in range(len(energy_df)):
        row = energy_df.iloc[index]
        time_str = row["Timestamp"].strftime("%H:%M:%S")
        power_val = float(row["Global_active_power"])
        voltage_val = float(row["Voltage"])

        # Son 30 veri noktasını hafızada tut
        st.session_state.history["time"].append(time_str)
        st.session_state.history["power"].append(power_val)
        if len(st.session_state.history["time"]) > 30:
            st.session_state.history["time"].pop(0)
            st.session_state.history["power"].pop(0)

        # 1. Metrik Kartlarını Güncelle
        is_peak = power_val > 4.0
        if is_peak:
            status_metric.error("⚠️ YÜKSEK TÜKETİM ALARMI!")
        else:
            status_metric.success("✅ NORMAL ÇALIŞMA")

        power_metric.metric("Aktif Güç", f"{power_val:.2f} kW")
        voltage_metric.metric("Şebeke Gerilimi", f"{voltage_val:.1f} V")

        # 2. Plotly Canlı Grafiği Çiz
        fig = go.Figure()
        fig.add_trace(
            go.Scatter(
                x=st.session_state.history["time"],
                y=st.session_state.history["power"],
                mode="lines+markers",
                name="Aktif Güç (kW)",
                line=dict(color="#38bdf8", width=3),
                fill="tozeroy",
                fillcolor="rgba(56, 189, 248, 0.1)",
            )
        )

        fig.update_layout(
            template="plotly_dark",
            height=400,
            margin=dict(l=20, r=20, t=30, b=20),
            xaxis_title="Zaman (Saat:Dakika:Saniye)",
            yaxis_title="Güç (kW)",
            yaxis=dict(range=[0, max(st.session_state.history["power"]) + 1]),
        )

        chart_spot.plotly_chart(fig, use_container_width=True)
        time.sleep(0.5)